version: '3.8'

services:
  postgres:
    container_name: petland_db_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=YOUR_USER
      - POSTGRES_PASSWORD=YOUR_PASSWORD
      - POSTGRES_DB=petland_db